# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator-{instance}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loadgenerator-{instance}
      mode: master
  template:
    metadata:
      labels:
        app: loadgenerator-{instance}
        mode: master
    spec:
      containers:
        - name: locust-main-{instance}
          image:     {image}
          imagePullPolicy: Always
          env:
            - name: LOCUST_MODE
              value: standalone
            - name: LOCUST_TASK
              value: basic
            - name: TARGET_HOST
              valueFrom:
                configMapKeyRef:
                  name: address-config
                  key: FRONTEND_ADDR
          ports:
            - name: loc-m-web-{instance}
              containerPort: 8089
              protocol: TCP
            - name: loc-m-api-{instance}
              containerPort: 8090
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: loadgenerator-{instance}
  labels:
    app: loadgenerator-{instance}
spec:
  ports:
    - port: 80
      targetPort: loc-m-web-{instance}
      protocol: TCP
      name: loc-m-web-{instance}
    - port: 81
      targetPort: loc-m-api-{instance}
      protocol: TCP
      name: loc-m-api-{instance}
  selector:
    app: loadgenerator-{instance}
    mode: master
  type: LoadBalancer
